Update build_hi1616_openwrt.yml

diff --git a/.github/workflows/build_hi1616_openwrt.yml b/.github/workflows/build_hi1616_openwrt.yml
--- a/.github/workflows/build_hi1616_openwrt.yml
+++ b/.github/workflows/build_hi1616_openwrt.yml
@@ -1,71 +1,253 @@
-ake[3] -C toolchain/gcc/final compile
- make[2] target/compile
- make[3] -C target/linux compile
-    ERROR: target/linux failed to build.
-make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
-make: *** [/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/include/toplevel.mk:233: world] Error 1
-make[2]: Entering directory '/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/scripts/config'
-make[2]: 'conf' is up to date.
-make[2]: Leaving directory '/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/scripts/config'
-make[1]: Entering directory '/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt'
-make[2]: Entering directory '/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt'
-+ mkdir -p /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/staging_dir/target-aarch64_generic_musl
-+ cd /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/staging_dir/target-aarch64_generic_musl
-+ mkdir -p bin lib stamp usr/include usr/lib
-mkdir -p /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/stamp
-touch /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/staging_dir/target-aarch64_generic_musl/.prepared
-make[3]: Entering directory '/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/target/linux'
-make[4]: Entering directory '/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/target/linux/armsr'
-rm -f /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/localversion
-/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/scripts/kconfig.pl  + + /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/target/linux/generic/config-5.15 /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/target/linux/armsr/config-5.15 /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/target/linux/armsr/armv8/config-5.15 > /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.target
-awk '/^(#[[:space:]]+)?CONFIG_KERNEL/{sub("CONFIG_KERNEL_","CONFIG_");print}' /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/.config >> /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.target
-echo "# CONFIG_KALLSYMS_EXTRA_PASS is not set" >> /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.target
-echo "# CONFIG_KALLSYMS_ALL is not set" >> /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.target
-echo "CONFIG_KALLSYMS_UNCOMPRESSED=y" >> /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.target
-/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/scripts/package-metadata.pl kconfig /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/tmp/.packageinfo /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/.config 5.15 > /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.override
-/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/scripts/kconfig.pl 'm+' '+' /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.target /dev/null /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.override > /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.set
-mv /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.set /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.old
-grep -v INITRAMFS /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.old > /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.set
-echo 'CONFIG_INITRAMFS_SOURCE=""' >> /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.set
-echo '# CONFIG_INITRAMFS_FORCE is not set' >> /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.set
-rm -rf /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/modules
-cmp -s /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.set /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.prev || { cp /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.set /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config; cp /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.set /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.prev; }
-export MAKEFLAGS= ; [ -d /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/user_headers ] || make -C /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198 KCFLAGS="-fmacro-prefix-map=/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl=target-aarch64_generic_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Fri Feb 27 02:46:17 2026" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.15.198 CC="aarch64-openwrt-linux-musl-gcc
-grep '=[ym]' /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.config.set | LC_ALL=C sort | /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/staging_dir/host/bin/mkhash md5 > /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.vermagic
-touch /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.configured
-rm -f /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/vmlinux /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/System.map
-make -C /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198 KCFLAGS="-fmacro-prefix-map=/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl=target-aarch64_generic_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Fri Feb 27 02:46:17 2026" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.15.198 CC="aarch64-openwrt-linux-musl-gcc" all modules
-make[5]: Entering directory '/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198'
-  SYNC    include/config/auto.conf.cmd
-.config:451:warning: override: ARM64_VA_BITS_48 changes choice state
-.config:3315:warning: override: IOMMU_DEFAULT_PASSTHROUGH changes choice state
-.config:5144:warning: override: NO_HZ_IDLE changes choice state
-*
-* Restart config...
-*
-*
-* SCSI Transports
-*
-Parallel SCSI (SPI) Transport Attributes (SCSI_SPI_ATTRS) [N/m/y/?] n
-FiberChannel Transport Attributes (SCSI_FC_ATTRS) [N/m/y/?] n
-iSCSI Transport Attributes (SCSI_ISCSI_ATTRS) [N/m/y/?] n
-SAS Transport Attributes (SCSI_SAS_ATTRS) [Y/?] y
-SAS Domain Transport Attributes (SCSI_SAS_LIBSAS) [Y/?] y
-  ATA support for libsas (requires libata) (SCSI_SAS_ATA) [Y/n/?] y
-make[7]: *** [scripts/kconfig/Makefile:77: syncconfig] Error 1
-make[6]: *** [Makefile:628: syncconfig] Error 2
-Makefile:725: include/config/auto.conf.cmd: No such file or directory
-make[5]: *** [Makefile:748: include/config/auto.conf.cmd] Error 2
-  Support for SMP interpretation for SAS hosts (SCSI_SAS_HOST_SMP) [Y/n/?] (NEW) make[5]: Leaving directory '/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198'
-make[4]: *** [Makefile:22: /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/build_dir/target-aarch64_generic_musl/linux-armsr_armv8/linux-5.15.198/.modules] Error 2
-make[3]: *** [Makefile:11: compile] Error 2
-make[4]: Leaving directory '/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/target/linux/armsr'
-make[3]: Leaving directory '/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/target/linux'
-time: target/linux/compile#0.87#0.60#1.43
-    ERROR: target/linux failed to build.
-make[2]: *** [target/Makefile:32: target/linux/compile] Error 1
-make[2]: Leaving directory '/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt'
-make[1]: *** [target/Makefile:25: /home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/staging_dir/target-aarch64_generic_musl/stamp/.target_compile] Error 2
-make[1]: Leaving directory '/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt'
-make: *** [/home/runner/work/My-C3958-Router/My-C3958-Router/openwrt/include/toplevel.mk:233: world] Error 2
-Error: Process completed with exit code 2.
+name: Build ImmortalWrt for HiSilicon PV660 SD100 (ARM64)
+
+on:
+  workflow_dispatch:
+
+jobs:
+  build:
+    runs-on: ubuntu-22.04
+
+    steps:
+    - name: 检查项目代码
+      uses: actions/checkout@v4
+
+    - name: 准备编译环境
+      env:
+        DEBIAN_FRONTEND: noninteractive
+      run: |
+        sudo apt-get update
+        sudo apt-get -y install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
+        gettext git libncurses5-dev libssl-dev python3-distutils python3-setuptools rsync unzip zlib1g-dev file wget xsltproc
+        sudo apt-get clean
+
+    - name: 拉取 ImmortalWrt 源码
+      run: |
+        git clone -b openwrt-23.05 --depth=1 https://github.com/immortalwrt/immortalwrt.git openwrt
+
+    - name: 更新并安装 Feeds
+      working-directory: ./openwrt
+      run: |
+        ./scripts/feeds update -a
+        ./scripts/feeds install -a
+
+    - name: 注入升级后的 DTB 文件
+      working-directory: ./openwrt
+      run: |
+        # 将升级适配 5.x 的 hisi_p660_evb.dtb 放入内核设备树搜索路径
+        # armsr 目标使用标准内核 DTB，我们覆盖到 files overlay 目录
+        DTB_DIR="target/linux/armsr/armv8/base-files/boot"
+        mkdir -p "$DTB_DIR"
+        cp ../dtb-5.x/hisi_p660_evb.dtb "$DTB_DIR/hisi_p660_evb.dtb"
+        echo "DTB 注入完成: $(ls -la $DTB_DIR/)"
+
+    - name: 生成 .config
+      working-directory: ./openwrt
+      run: |
+        cat <<'EOF' > .config
+        # ==========================================
+        # 1. 目标平台: armsr ARM64
+        # ==========================================
+        CONFIG_TARGET_armsr=y
+        CONFIG_TARGET_armsr_armv8=y
+        CONFIG_TARGET_armsr_armv8_DEVICE_generic=y
+
+        # ==========================================
+        # 2. LuCI 与中文
+        # ==========================================
+        CONFIG_PACKAGE_luci=y
+        CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
+
+        # ==========================================
+        # 3. OpenClash
+        # ==========================================
+        CONFIG_PACKAGE_luci-app-openclash=y
+        CONFIG_PACKAGE_dnsmasq-full=y
+        CONFIG_PACKAGE_ca-bundle=y
+        CONFIG_PACKAGE_curl=y
+
+        # ==========================================
+        # 4. HNS 网卡驱动 (必须内建，否则无网络)
+        # ==========================================
+        CONFIG_PACKAGE_kmod-hns=y
+        CONFIG_PACKAGE_kmod-hns3=y
+        EOF
+
+        make defconfig
+
+    - name: 注入海思平台内核配置
+      working-directory: ./openwrt
+      run: |
+        # 找到内核配置文件
+        KERNEL_CONF="target/linux/armsr/armv8/config-5.15"
+        [ -f "$KERNEL_CONF" ] || KERNEL_CONF=$(find target/linux/armsr -name "config-5.15" | head -n1)
+
+        if [ -z "$KERNEL_CONF" ] || [ ! -f "$KERNEL_CONF" ]; then
+          echo "ERROR: 找不到内核配置文件"
+          exit 1
+        fi
+
+        echo "内核配置文件: $KERNEL_CONF"
+
+        # 追加 HiP05/PV660 必需的内核配置
+        cat >> "$KERNEL_CONF" <<'EOF'
+
+        # =============================================
+        # HiSilicon HiP05 / PV660 / SD100 平台驱动
+        # =============================================
+
+        # --- 海思 HNS 网卡 (内建，开机必须可用) ---
+        CONFIG_NET_VENDOR_HISILICON=y
+        CONFIG_HISILICON_HNS=y
+        CONFIG_HISILICON_HNS_DSAF=y
+        CONFIG_HISILICON_HNS_ENET=y
+        CONFIG_HNS=y
+        CONFIG_HNS_DSAF=y
+        CONFIG_HNS_ENET=y
+        CONFIG_HNS3=y
+        CONFIG_HNS3_HCLGE=y
+        CONFIG_HNS3_ENET=y
+        CONFIG_HNS_MDIO=y
+
+        # --- 串口控制台 ---
+        CONFIG_SERIAL_8250=y
+        CONFIG_SERIAL_8250_DW=y
+        CONFIG_SERIAL_8250_CONSOLE=y
+        CONFIG_SERIAL_AMBA_PL011=y
+        CONFIG_SERIAL_AMBA_PL011_CONSOLE=y
+        CONFIG_CONSOLE_POLL=y
+
+        # --- PCIe (HiSilicon hip05/hip06 控制器) ---
+        CONFIG_PCI_HISI=y
+        CONFIG_PCIEPORTBUS=y
+        CONFIG_PCI_HOST_GENERIC=y
+
+        # --- SATA/SAS 存储 ---
+        CONFIG_ATA=y
+        CONFIG_ATA_PIIX=y
+        CONFIG_SATA_AHCI=y
+        CONFIG_SATA_AHCI_PLATFORM=y
+        CONFIG_SCSI=y
+        CONFIG_BLK_DEV_SD=y
+        CONFIG_SCSI_HISI_SAS=y
+        CONFIG_SCSI_HISI_SAS_V2_HW=y
+        CONFIG_SCSI_SAS_ATA=y
+        CONFIG_SCSI_SAS_ATTRS=y
+        CONFIG_SCSI_SAS_LIBSAS=y
+        CONFIG_SCSI_SAS_HOST_SMP=y
+        CONFIG_SCSI_MPT3SAS=y
+
+        # --- USB (DesignWare DWC3) ---
+        CONFIG_USB_DWC3=y
+        CONFIG_USB_DWC3_DUAL_ROLE=y
+
+        # --- GPIO / I2C / LPC ---
+        CONFIG_GPIO_DWAPB=y
+        CONFIG_I2C_DESIGNWARE_PLATFORM=y
+        CONFIG_HISILICON_LPC=y
+
+        # --- 系统控制器 / Regmap ---
+        CONFIG_MFD_SYSCON=y
+        CONFIG_REGMAP_MMIO=y
+        CONFIG_REGMAP=y
+
+        # --- 电源 / 热管理 / PMU ---
+        CONFIG_POWER_RESET_HISI=y
+        CONFIG_HISI_THERMAL=y
+        CONFIG_HISI_PMU=y
+
+        # --- 硬件随机数 (OpenClash TLS 需要) ---
+        CONFIG_HW_RANDOM_HISI=y
+        CONFIG_HW_RANDOM=y
+
+        # --- EFI DTB 覆盖 (允许 GRUB devicetree 命令生效) ---
+        CONFIG_EFI_ARMSTUB_DTB_LOADER=y
+
+        # --- RTC (板载 ds3231) ---
+        CONFIG_RTC_DRV_DS1307=y
+        CONFIG_RTC_CLASS=y
+
+        # --- EDAC (启动日志中可见 edac_hha_c 等) ---
+        CONFIG_EDAC=y
+        CONFIG_EDAC_MM_EDAC=y
+
+        # --- MD RAID (原系统用了 md, 保留兼容) ---
+        CONFIG_MD=y
+        CONFIG_BLK_DEV_MD=y
+        CONFIG_MD_RAID1=y
+
+        # --- Bonding (原系统用了 bond0) ---
+        CONFIG_BONDING=y
+        EOF
+
+        echo "内核配置追加完成"
+
+    - name: 修改 GRUB 引导配置 (注入 DTB + 串口控制台)
+      working-directory: ./openwrt
+      run: |
+        GRUB_CFG="target/linux/armsr/image/grub-efi.cfg"
+
+        if [ ! -f "$GRUB_CFG" ]; then
+          echo "ERROR: 找不到 grub-efi.cfg"
+          find target/linux/armsr -name "grub*" 2>/dev/null
+          exit 1
+        fi
+
+        echo "=== 原 GRUB 配置 ==="
+        cat "$GRUB_CFG"
+
+        # 在 linux 行之前插入 devicetree 命令，并确保 console 参数正确
+        cat > "$GRUB_CFG" <<'GRUBEOF'
+        menuentry "@TITLE@" {
+            search --set=root --label kernel
+            devicetree /boot/hisi_p660_evb.dtb
+            linux /efi/openwrt/@KERNEL_NAME@ @GPT_ROOTPART@ @CMDLINE@ console=ttyS0,115200 earlycon=uart8250,mmio32,0x60300000 noinitrd
+        }
+        GRUBEOF
+
+        echo ""
+        echo "=== 新 GRUB 配置 ==="
+        cat "$GRUB_CFG"
+
+    - name: 确保构建系统复制 boot 目录到 EFI 分区
+      working-directory: ./openwrt
+      run: |
+        # 检查 image/Makefile 中是否有 boot 目录复制逻辑
+        IMAGE_MK="target/linux/armsr/image/Makefile"
+        if grep -q 'boot' "$IMAGE_MK"; then
+          echo "image/Makefile 已包含 boot 目录处理"
+          grep -n 'boot' "$IMAGE_MK"
+        else
+          echo "注意: image/Makefile 中没有明确的 boot 目录处理"
+          echo "依赖 base-files overlay 机制自动复制"
+        fi
+
+    - name: 下载源码包
+      working-directory: ./openwrt
+      run: make download -j8
+
+    - name: 预编译内核配置 (自动解决未解析依赖)
+      working-directory: ./openwrt
+      run: |
+        # 先让 OpenWrt 准备好内核源码和 .config
+        make target/linux/prepare V=s || true
+        # 找到内核源码目录并运行 olddefconfig 自动补全所有依赖
+        KDIR=$(find build_dir -maxdepth 4 -name linux-5.15.* -type d | head -1)
+        if [ -n "$KDIR" ] && [ -d "$KDIR" ]; then
+          echo "内核源码: $KDIR"
+          cd "$KDIR"
+          make ARCH=arm64 olddefconfig </dev/null
+          echo "olddefconfig 完成"
+        else
+          echo "WARNING: 未找到内核源码目录，跳过 olddefconfig"
+        fi
+
+    - name: 编译固件
+      working-directory: ./openwrt
+      run: |
+        make -j$(nproc) || make -j1 V=s
+
+    - name: 上传固件
+      uses: actions/upload-artifact@v4
+      with:
+        name: ImmortalWrt-PV660-SD100-ARM64
+        path: openwrt/bin/targets/armsr/armv8/*
